name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# 添加权限配置
permissions:
  contents: write # 添加写入权限

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: true # 修改为 true 以保持凭证

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: ^8.0

      - name: Install Deps
        run: pnpm i --no-frozen-lockfile

      - name: Format
        run: pnpm format

      - name: Lint
        run: pnpm lint

      - name: Generate Prisma
        run: pnpm --filter next-blog exec prisma generate

      - name: Build
        run: pnpm build

      # 添加 nest-server 打包步骤
      - name: Build nest-server
        run: pnpm --filter nest-server build:prod

      # 配置 Git
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      # 提交更改
      - name: Commit changes
        run: |
          git add apps/nest-server/api/index.js
          git commit -m "chore: update nest-server api build" || echo "No changes to commit"
          git push
